// Knowledge base: read-only documentation of the QKB Python measurement algorithms
// (today only CRR). Content comes from crr_manifest.json, generated by
// `python -m crr.manifest` in backend/QKB/CRR — nothing here runs an algorithm.
import manifest from './crr_manifest.json';
import { $, esc } from './util.js';

const algos = Array.isArray(manifest.algorithms) ? manifest.algorithms : [];
const ui = { q: '', selected: algos.length ? algos[0].id : null };

const table = (head, rows) => `<table><thead><tr>${head.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const list = items => `<ul class="plain">${items.map(i => `<li>${esc(i)}</li>`).join('')}</ul>`;
const mono = v => `<span class="mono">${esc(v)}</span>`;

function matches(a, q) {
  if (!q) return true;
  return [a.id, a.name, a.summary, a.intended_use, a.evidence_type].some(s => String(s || '').toLowerCase().includes(q));
}

function detail(a) {
  const o = a.outputs || {};
  return `<article>
    <header><h2>${esc(a.name)}</h2>
      <div class="meta"><span class="mono">${esc(a.id)}@${esc(a.version)}</span><span class="tag py">Python</span><span class="tag ev">Evidence · ${esc(String(a.evidence_type).toUpperCase())}</span></div>
      <div class="dim mono small">${esc(a.package)} · 規格 ${esc(a.spec)}</div></header>
    <p>${esc(a.summary)}</p>
    <h4>適用情境</h4><p>${esc(a.intended_use)}</p>
    <h4>方法</h4><ol class="plain">${(a.method || []).map(s => `<li>${esc(s)}</li>`).join('')}</ol>
    <h4>輸入</h4>${table(['名稱', '型別', '必填', '說明'], (a.inputs || []).map(i => [mono(i.name), esc(i.type), i.required ? '是' : '否', esc(i.description)]))}
    <h4>Mask 來源</h4>${table(['來源', '入口', '備註'], (a.mask_sources || []).map(s => [esc(s.label), mono(s.entry), esc(s.note)]))}
    <h4>參數</h4>${table(['名稱', '預設', '限制', '說明'], (a.params || []).map(p => [mono(p.name), mono(JSON.stringify(p.default)), esc(p.constraint), esc(p.description)]))}
    <h4>輸出指標（metrics）</h4>${table(['欄位', '單位', '說明', '何時有值'], (o.metrics || []).map(m => [mono(m.key), esc(m.unit), esc(m.description), esc(m.when)]))}
    <p class="dim small">另含 geometry：${(o.geometry || []).map(mono).join(' ')}；profile：${(o.profile || []).map(mono).join(' ')}；報告額外欄位：${(o.report_extras || []).map(mono).join(' ')}。schema ${mono(o.schema)}</p>
    <h4>狀態碼</h4>${table(['status', '說明'], (a.statuses || []).map(s => [mono(s.code), esc(s.description)]))}
    <h4>Evidence 圖層</h4><p>${(a.evidence_layers || []).map(l => `<span class="tag ev">${esc(l)}</span>`).join(' ')}</p>
    <h4>使用方式</h4><pre class="code">${esc(a.usage.python)}\n\n${esc(a.usage.cli)}</pre>
    <h4>限制</h4>${list(a.limitations || [])}
    <p class="dim small">研究用途；此頁只說明演算法，不代表診斷或方法效度證明。</p>
  </article>`;
}

function draw() {
  const q = ui.q.trim().toLowerCase();
  const shown = algos.filter(a => matches(a, q));
  $('#kb-count').textContent = `${shown.length} 個量測演算法`;
  $('#kb-list').innerHTML = shown.length
    ? shown.map(a => `<li><button type="button" class="row-btn${a.id === ui.selected ? ' on' : ''}" data-id="${esc(a.id)}"><span class="name">${esc(a.name)}</span><span class="meta"><span class="mono">${esc(a.id)}@${esc(a.version)}</span><span class="tag py">Python</span></span><span class="sum">${esc(a.summary)}</span></button></li>`).join('')
    : '<li class="empty">沒有符合的演算法。</li>';
  const cur = shown.find(a => a.id === ui.selected);
  $('#kb-detail').innerHTML = cur ? detail(cur) : '<div class="empty big">選擇一個演算法以查看方法、輸入輸出與限制。</div>';
}

export function initKb() {
  $('#kb-q').addEventListener('input', ev => { ui.q = ev.target.value; draw(); });
  $('#kb-list').addEventListener('click', ev => {
    const b = ev.target.closest('[data-id]');
    if (b) { ui.selected = b.getAttribute('data-id'); draw(); }
  });
  draw();
}
